apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: bs-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /v1.2/$1/$3
spec:
  rules:
  - host: demo.bigstream.cloud
    http:
      paths:
      - backend:
          serviceName: main-bigstream
          servicePort: 19980
        path: /bs/(jobs|info)(/|$)(.*)
      - backend:
          serviceName: main-bigstream
          servicePort: 19080
        path: /bs/(storage|object)(/|$)(.*)
