apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bs-pvclaim
  labels:
    app: bigstream
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvclaim
  labels:
    app: bigstream 
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  resources:
    requests:
      storage: 8Gi